spring:
  application:
    name: microservice-simple-consumer-movie

server:
  port: 8010

info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@

eureka:
  client:
    serviceUrl:
      defaultZone: http://linjk:ljk121@peer1:8761/eureka/
  instance:
    prefer-ip-address: true