# Usage: java -jar microservice-discovery-eureka.jar --spring.profile.active=peer1(2)

spring:
  application:
    name: microservice-discovery-eureka
security:
  basic:
    enabled: true
  user:
    name: linjk
    password: ljk121


---

spring:
  profiles: peer1

server:
  port: 8761

eureka:
  instance:
    hostname: peer1
  client:
    service-url:
      defaultZone: http://linjk:ljk121@peer2:8762/eureka/

---

spring:
  profiles: peer2

server:
  port: 8762

eureka:
  instance:
    hostname: peer2
  client:
    service-url:
      defaultZone: http://linjk:ljk121@peer1:8761/eureka/
