server:
  port: 8761

# 说明：
# 1. register-with-eureka： 不把自己注册到erueka，因为已经是其本身
# 2. fetch-registry      ： 不从eureka server获取注册信息，目前只有一个节点
# 3. defaultZone         ： 配置服务中心的地址
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
